name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0'
    
    - name: Build Auto2FA
      run: |
        xcodebuild -project Auto2FA.xcodeproj -scheme Auto2FA -configuration Debug build
    
    - name: Build Auto2FAExtension
      run: |
        xcodebuild -project Auto2FA.xcodeproj -scheme Auto2FAExtension -configuration Debug build
    
    - name: Run SwiftLint
      run: |
        brew install swiftlint
        swiftlint lint
        
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0'
    
    - name: Run Tests
      run: |
        xcodebuild -project Auto2FA.xcodeproj -scheme Auto2FA -configuration Debug test 